// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmGSvfNpsHa2CeV7JtFPWV2kQ5DlPo-98',
    appId: '1:1096445344679:web:94d8b8aa0d82ef09eb9482',
    messagingSenderId: '1096445344679',
    projectId: 'fir-login-page-9f69d',
    authDomain: 'fir-login-page-9f69d.firebaseapp.com',
    storageBucket: 'fir-login-page-9f69d.appspot.com',
    measurementId: 'G-KLTWQ3X1PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIETZ7hWDzKMfOSdoVJfEQ9TIZ4m-VBk0',
    appId: '1:1096445344679:android:563afc47de081576eb9482',
    messagingSenderId: '1096445344679',
    projectId: 'fir-login-page-9f69d',
    storageBucket: 'fir-login-page-9f69d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB89T5mNjp8PEsnDKCzUT6Uwt3WbFpGMmA',
    appId: '1:1096445344679:ios:df948c1b3557d36eeb9482',
    messagingSenderId: '1096445344679',
    projectId: 'fir-login-page-9f69d',
    storageBucket: 'fir-login-page-9f69d.appspot.com',
    iosClientId: '1096445344679-a5pjbukffi1mgruf36qcblcjhp5ut8b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB89T5mNjp8PEsnDKCzUT6Uwt3WbFpGMmA',
    appId: '1:1096445344679:ios:c660803810826e7feb9482',
    messagingSenderId: '1096445344679',
    projectId: 'fir-login-page-9f69d',
    storageBucket: 'fir-login-page-9f69d.appspot.com',
    iosClientId: '1096445344679-i492o2um67jsafbnsgjchb5scm1afrk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginPage.RunnerTests',
  );
}
